export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

export const FOOTERCATEGORY_LIST_REQUEST = 'FOOTERCATEGORY_LIST_REQUEST'
export const FOOTERCATEGORY_LIST_SUCCESS = 'FOOTERCATEGORY_LIST_SUCCESS'
export const FOOTERCATEGORY_LIST_FAIL = 'FOOTERCATEGORY_LIST_FAIL'



export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST'
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS'
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL'


export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST'
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS'
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL'


export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST'
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS'
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL'
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET'


export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST'
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET'




export const TOPCATEGORY_LIST_REQUEST = 'TOPCATEGORY_LIST_REQUEST'
export const TOPCATEGORY_LIST_SUCCESS = 'TOPCATEGORY_LIST_SUCCESS'
export const TOPCATEGORY_LIST_FAIL = 'TOPCATEGORY_LIST_FAIL'



export const TOPCATEGORY_DETAILS_REQUEST = 'TOPCATEGORY_DETAILS_REQUEST'
export const TOPCATEGORY_DETAILS_SUCCESS = 'TOPCATEGORY_DETAILS_SUCCESS'
export const TOPCATEGORY_DETAILS_FAIL = 'TOPCATEGORY_DETAILS_FAIL'


export const TOPCATEGORY_DELETE_REQUEST = 'TOPCATEGORY_DELETE_REQUEST'
export const TOPCATEGORY_DELETE_SUCCESS = 'TOPCATEGORY_DELETE_SUCCESS'
export const TOPCATEGORY_DELETE_FAIL = 'TOPCATEGORY_DELETE_FAIL'


export const TOPCATEGORY_CREATE_REQUEST = 'TOPCATEGORY_CREATE_REQUEST'
export const TOPCATEGORY_CREATE_SUCCESS = 'TOPCATEGORY_CREATE_SUCCESS'
export const TOPCATEGORY_CREATE_FAIL = 'TOPCATEGORY_CREATE_FAIL'
export const TOPCATEGORY_CREATE_RESET = 'TOPCATEGORY_CREATE_RESET'


export const TOPCATEGORY_UPDATE_REQUEST = 'TOPCATEGORY_UPDATE_REQUEST'
export const TOPCATEGORY_UPDATE_SUCCESS = 'TOPCATEGORY_UPDATE_SUCCESS'
export const TOPCATEGORY_UPDATE_FAIL = 'TOPCATEGORY_UPDATE_FAIL'
export const TOPCATEGORY_UPDATE_RESET = 'TOPCATEGORY_UPDATE_RESET'