export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'


export const ORDER_CREATE_REQUEST_EVC = 'ORDER_CREATE_REQUEST_EVC'
export const ORDER_CREATE_SUCCESS_EVC = 'ORDER_CREATE_SUCCESS_EVC'
export const ORDER_CREATE_FAIL_EVC = 'ORDER_CREATE_FAIL_EVC'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'


export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_EVC_PAY_REQUEST = 'ORDER_EVC_PAY_REQUEST'
export const ORDER_EVC_PAY_SUCCESS = 'ORDER_EVC_PAY_SUCCESS' 
export const ORDER_EVC_PAY_FAIL = 'ORDER_EVC_PAY_FAIL'
export const ORDER_EVC_PAY_RESET = 'ORDER_EVC_PAY_RESET'

export const ORDER_PAY_REQUEST2 = 'ORDER_PAY_REQUEST2'
export const ORDER_PAY_SUCCESS2 = 'ORDER_PAY_SUCCESS2'
export const ORDER_PAY_FAIL2 = 'ORDER_PAY_FAIL2'
export const ORDER_PAY_RESET2 = 'ORDER_PAY_RESET2'

export const ORDER_MY_LIST_REQUEST = 'ORDER_MY_LIST_REQUEST'
export const ORDER_MY_LIST_SUCCESS = 'ORDER_MY_LIST_SUCCESS'
export const ORDER_MY_LIST_FAIL = 'ORDER_MY_LIST_FAIL'
export const ORDER_MY_LIST_RESET = 'ORDER_MY_LIST_RESET'


export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const RECENTORDER_LIST_REQUEST = 'RECENTORDER_LIST_REQUEST'
export const RECENTORDER_LIST_SUCCESS = 'RECENTORDER_LIST_SUCCESS'
export const RECENTORDER_LIST_FAIL = 'RECENTORDER_LIST_FAIL'

export const ORDER_LIST_REQUEST2 = 'ORDER_LIST_REQUEST2'
export const ORDER_LIST_SUCCESS2 = 'ORDER_LIST_SUCCESS2'
export const ORDER_LIST_FAIL2 = 'ORDER_LIST_FAIL2'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'
