export const SETTINGS_LIST_REQUEST = 'SETTINGS_LIST_REQUEST'
export const SETTINGS_LIST_SUCCESS = 'SETTINGS_LIST_SUCCESS'
export const SETTINGS_LIST_FAIL = 'SETTINGS_LIST_FAIL'

export const SETTINGS_DELETE_REQUEST = 'SETTINGS_DELETE_REQUEST'
export const SETTINGS_DELETE_SUCCESS = 'SETTINGS_DELETE_SUCCESS'
export const SETTINGS_DELETE_FAIL = 'SETTINGS_DELETE_FAIL'

export const SETTINGS_UPDATE_REQUEST = 'SETTINGS_UPDATE_REQUEST'
export const SETTINGS_UPDATE_SUCCESS = 'SETTINGS_UPDATE_SUCCESS'
export const SETTINGS_UPDATE_FAIL = 'SETTINGS_UPDATE_FAIL'
export const SETTINGS_UPDATE_RESET = 'SETTINGS_UPDATE_RESET'


export const SETTINGS_DETAILS_REQUEST = 'SETTINGS_DETAILS_REQUEST'
export const SETTINGS_DETAILS_SUCCESS = 'SETTINGS_DETAILS_SUCCESS'
export const SETTINGS_DETAILS_FAIL = 'SETTINGS_DETAILS_FAIL'
export const SETTINGS_DETAILS_RESET = 'SETTINGS_DETAILS_RESET'



export const SETTINGS_CREATE_REQUEST = 'SETTINGS_CREATE_REQUEST'
export const SETTINGS_CREATE_SUCCESS = 'SETTINGS_CREATE_SUCCESS'
export const SETTINGS_CREATE_FAIL = 'SETTINGS_CREATE_FAIL'
export const SETTINGS_CREATE_RESET = 'SETTINGS_CREATE_RESET'
